// RASCUNHO: texto de interface ainda sem revisão do guardião da marca. Não é texto final.
// Fonte: docs/mvp/experiencia.md (seções 4.1, 4.3 e 6) e docs/marca/identidade.md.
// Voz: rótulo do sistema em voz neutra; fala do Otto em primeira pessoa (pergunta (a) da seção 6,
// ainda sem resposta do guardião). Nada de nome de modelo, token ou custo.

export const editor = {
  tituloDaPagina: (peca: string | undefined): string => (peca ? `${peca} · Otto` : 'Otto'),
  carregando: 'Abrindo o editor…',

  topo: {
    rotulo: 'Barra do editor',
    marca: 'Otto',
    caminho: 'Caminho da peça',
    pecas: 'Peças',
    pecaSemNome: 'Peça',
    desfazer: 'Desfazer',
    refazer: 'Refazer',
    atalhoDeDesfazer: 'Ctrl+Z',
    atalhoDeRefazer: 'Ctrl+Shift+Z',
    paineis: 'Painéis',
    dicaDosPaineis: 'Esconder e mostrar os painéis (Tab, com o foco no canvas)',
    exportar: 'Exportar',
    salvamento: { salvo: 'salvo', salvando: 'salvando…', 'sem-conexao': 'sem conexão', leitura: 'só leitura' },
    avisosDoRender: (n: number): string => (n === 1 ? '1 aviso do canvas' : `${n} avisos do canvas`),
  },

  /** O que o canvas deixou de mostrar. Discreto, mas nunca escondido. */
  render: {
    fontes: 'Fontes que não carregaram',
    fonte: (familia: string, peso: number, camadas: string): string => `${familia} ${peso}: o texto de ${camadas} não aparece no canvas.`,
    imagens: 'Imagens que não carregaram',
    imagem: (camadas: string): string => `A imagem de ${camadas} aparece como um retângulo cinza.`,
    naoDesenhado: 'Ainda não desenhado pelo canvas',
    recurso: (recurso: string, camadas: string): string => `${recurso}: ${camadas}. A camada aparece sem ele; o documento não muda.`,
    fechar: 'Fechar os avisos',
  },

  ferramentas: {
    rotulo: 'Ferramentas',
    mover: { nome: 'Mover', tecla: 'V' },
    mao: { nome: 'Mão', tecla: 'H' },
    zoom: { nome: 'Zoom', tecla: 'Z' },
    comTecla: (nome: string, tecla: string): string => `${nome} (${tecla})`,
  },

  paineis: {
    otto: {
      titulo: 'Otto',
      vazio: 'Nenhuma tarefa nesta peça. As etapas do trabalho, a revisão das alterações e o pedido de ajuste aparecem aqui.',
    },
    propriedades: {
      titulo: 'Propriedades',
      vazio: 'Selecione uma camada ou prancheta.',
    },
    camadas: {
      titulo: 'Camadas',
      vazio: 'Nenhuma prancheta ainda.',
    },
  },

  /** Nomes dos modos de mesclagem, como no Photoshop em português. */
  mesclagem: {
    atravessar: 'Atravessar',
    normal: 'Normal',
    escurecer: 'Escurecer',
    multiplicacao: 'Multiplicação',
    'subexposicao-de-cores': 'Subexposição de cores',
    'subexposicao-linear': 'Subexposição linear',
    'cor-mais-escura': 'Cor mais escura',
    clarear: 'Clarear',
    tela: 'Divisão',
    'superexposicao-de-cores': 'Superexposição de cores',
    'superexposicao-linear': 'Superexposição linear (adicionar)',
    'cor-mais-clara': 'Cor mais clara',
    sobrepor: 'Sobrepor',
    'luz-suave': 'Luz suave',
    'luz-direta': 'Luz direta',
    'luz-intensa': 'Luz intensa',
    'luz-linear': 'Luz linear',
    'luz-do-ponto': 'Luz do ponto',
    'mistura-solida': 'Mistura sólida',
    diferenca: 'Diferença',
    exclusao: 'Exclusão',
    subtrair: 'Subtrair',
    dividir: 'Dividir',
    matiz: 'Matiz',
    saturacao: 'Saturação',
    cor: 'Cor',
    luminosidade: 'Luminosidade',
  },

  camadas: {
    recolher: 'Recolher grupo',
    abrir: 'Abrir grupo',
    ocultar: 'Ocultar',
    mostrar: 'Mostrar',
    bloquear: 'Bloquear (o Otto não mexe)',
    desbloquear: 'Desbloquear',
    paraAFrente: 'Trazer para a frente',
    paraTras: 'Enviar para trás',
    atalhoParaAFrente: 'Ctrl+]',
    atalhoParaTras: 'Ctrl+[',
    novoNome: (camada: string): string => `Novo nome de ${camada}`,
    tipos: { texto: 'texto', forma: 'forma', imagem: 'imagem', vetor: 'vetor', grupo: 'grupo', ajuste: 'camada de ajuste' },
    linha: (nome: string, tipo: string): string => `${nome}, ${tipo}`,
    prancheta: (nome: string, largura: number, altura: number): string => `${nome}, prancheta ${largura}×${altura}`,
    comMascara: 'com máscara',
    recortada: 'máscara de recorte na camada de baixo',
  },

  canvas: {
    rotulo: 'Canvas da peça',
    enquadrar: 'Enquadrar',
    dicaDeEnquadrar: 'Enquadrar tudo (Ctrl+0)',
    zoom: 'Zoom',
    porcentagem: (zoom: number): string => `${Math.round(zoom * 100)}%`,
    zonaDaInterface: 'zona da interface: sem texto',
    abrindo: 'Abrindo a peça…',
    naoEncontrada: 'Não encontrei esta peça.',
    naoAbriu: 'Não consegui abrir esta peça.',
    tentarDeNovo: 'Tentar de novo',
    voltarParaPecas: 'Voltar para Peças',
  },

  /** Descrição de cada lote, como aparece no histórico da peça. */
  historico: {
    mover: (camada: string): string => `mover ${camada}`,
    remover: (camada: string): string => `remover ${camada}`,
    ocultar: (camada: string): string => `ocultar ${camada}`,
    mostrar: (camada: string): string => `mostrar ${camada}`,
    bloquear: (camada: string): string => `bloquear ${camada}`,
    desbloquear: (camada: string): string => `desbloquear ${camada}`,
    renomear: (de: string, para: string): string => `renomear ${de} para ${para}`,
    paraAFrente: (camada: string): string => `trazer ${camada} para a frente`,
    paraTras: (camada: string): string => `enviar ${camada} para trás`,
    alterar: (propriedade: string, camada: string): string => `${propriedade.toLowerCase()} de ${camada}`,
  },

  propriedades: {
    nome: 'Nome',
    x: 'X',
    y: 'Y',
    largura: 'L',
    altura: 'A',
    rotacao: 'Rotação °',
    opacidade: 'Opacidade %',
    mesclagem: 'Mesclagem',
    conteudo: 'Conteúdo',
    fonte: 'Fonte',
    peso: 'Peso',
    pesos: { 300: 'Leve', 400: 'Regular', 500: 'Médio', 600: 'Seminegrito', 700: 'Negrito' },
    tamanho: 'Tamanho px',
    entrelinha: 'Entrelinha',
    tracking: 'Tracking',
    alinhamento: 'Alinhamento',
    alinhamentos: { esquerda: 'Esquerda', centro: 'Centro', direita: 'Direita' },
    caixaAlta: 'Caixa alta',
    siglaDeCaixaAlta: 'AA',
    cor: 'Cor',
    preenchimento: 'Preenchimento',
    degrade: 'Degradê (edição pelo painel ainda não disponível)',
    raio: 'Raio',
    ajuste: 'Ajuste',
    ajustes: { cobrir: 'Cobrir', conter: 'Conter' },
    focoX: 'Foco X %',
    focoY: 'Foco Y %',
    zoomDaFoto: 'Zoom %',
    fundo: 'Fundo',
    corSolta: (valor: string): string => `${valor} (solta)`,
    token: (nome: string, valor: string): string => `token ${nome} · ${valor}`,
    seletorDeCor: (rotulo: string): string => `${rotulo}: cor`,
    seletorDeToken: (rotulo: string): string => `${rotulo}: token`,
    grupos: {
      prancheta: 'Prancheta',
      texto: 'Camada de texto',
      forma: 'Forma',
      imagem: 'Imagem',
      vetor: 'Vetor',
      grupo: 'Grupo',
      ajuste: 'Camada de ajuste',
      tipografia: 'Texto',
    },
    variasCamadas: (n: number): string => `${n} camadas selecionadas. As propriedades aparecem com uma camada só.`,
    bloqueada: 'Camada bloqueada. Desbloqueie na lista de camadas para editar.',
    foraDoPainel: 'Máscara, efeitos, filtros e ajuste de cor ainda não são editados por este painel.',
  },

  avisos: {
    fechar: 'Fechar aviso',
    semWebGL: {
      titulo: 'Este navegador está sem aceleração gráfica (WebGL).',
      texto: 'Sem ela o canvas fica lento demais para editar, então a peça não abre assim. Ligue a aceleração de hardware nas configurações do navegador e recarregue a página.',
    },
    contextoPerdido: {
      titulo: 'O navegador interrompeu a aceleração gráfica do canvas.',
      texto: 'A peça está salva. Recarregue a página para voltar a ver o canvas.',
    },
    motorNaoCarregou: {
      titulo: 'Não consegui carregar o canvas.',
      texto: 'A peça está salva. Recarregue a página para tentar de novo.',
    },
    recarregar: 'Recarregar',
    telaEstreita: 'Para revisar e editar, abra no computador.',
  },
} as const;
